#!/bin/bash

source /usr/share/git/completion/git-completion.bash

. <(kubectl completion bash)
complete -o default -F __start_kubectl k

source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

. <(lxc completion bash)

. <(flux completion bash)
